### ISSUE TITLE
havsfunc build error

### ISSUE THREAD

**Issue by aidalgol** [tadeokondrak/vs-overlay#6]
The `havsfunc` plugin fails to build.

### Steps to reproduce
Create the following `shell.nix` file
```nix
{ pkgs ? import <nixpkgs>
  {
    overlays = [
      (import (builtins.fetchTarball "https://github.com/tadeokondrak/vs-overlay/archive/master.tar.gz"))
    ];
    config = {
      allowUnfree = true;
    };
  }
}:
  pkgs.mkShell {
    nativeBuildInputs = with pkgs; [
      (vapoursynth.withPlugins (with vapoursynthPlugins; [
        havsfunc
      ]))
    ];
}
```
Then run `nix-shell`
```console
$ nix-shell
[...]
error: builder for '/nix/store/x0rk6bx30mi8dnzn4yd43znjnrb6mjd1-vapoursynth-bm3d-r8.drv' failed with exit code 1;
error: builder for '/nix/store/x0rk6bx30mi8dnzn4yd43znjnrb6mjd1-vapoursynth-bm3d-r8.drv' failed with exit code 1;
       last 10 log lines:
       >   119 |     L2Wiener = Max(std::numeric_limits<float>::epsilon(), L2Wiener);
       >       |                                        ^~~~~
       > [3/10] Compiling C++ object libbm3d.so.p/source_BM3D_Final.cpp.o
       > [4/10] Compiling C++ object libbm3d.so.p/source_BM3D_Basic.cpp.o
       > [5/10] Compiling C++ object libbm3d.so.p/source_VBM3D_Basic.cpp.o
       > [6/10] Compiling C++ object libbm3d.so.p/source_VAggregate.cpp.o
       > [7/10] Compiling C++ object libbm3d.so.p/source_VSPlugin.cpp.o
       > [8/10] Compiling C++ object libbm3d.so.p/source_BM3D_Base.cpp.o
       > [9/10] Compiling C++ object libbm3d.so.p/source_VBM3D_Base.cpp.o
       > ninja: build stopped: subcommand failed.
       For full logs, run 'nix log /nix/store/x0rk6bx30mi8dnzn4yd43znjnrb6mjd1-vapoursynth-bm3d-r8.drv'.
error: 1 dependencies of derivation '/nix/store/fbznd55bilv2z1a809mvsii36cciz84x-python3.9-havsfunc-r33.drv' failed to build
error: 1 dependencies of derivation '/nix/store/zah6am16838badjlykn850abnc6h3bza-python3.9-mvsfunc-r8.drv' failed to build
error: 1 dependencies of derivation '/nix/store/31xh78dzg9z43307xdpka7pa6wjxv5cm-vapoursynth-nix-plugins.c.drv' failed to build
error: 1 dependencies of derivation '/nix/store/3b7jsxp99ram8z311ff07iy3bddr62c5-vapoursynth-plugins-env.drv' failed to build
error: 1 dependencies of derivation '/nix/store/6q4w27fzs16hk4f7il5aa6vf2451fkh5-vapoursynth-58-with-plugins.drv' failed to build
```
<details><summary>Full nix log</summary>
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/6f3rk4zid5hc8md0b8qgjh3vxvkzz93v-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
meson flags: --buildtype=plain         --libdir=/nix/store/b1mwam4g25skl7r408phcvqhbn3i1sf0-vapoursynth-bm3d-r8/lib --libexecdir=/nix/store/b1mwam4g25skl7r408phcvqhbn3i1sf0-vapoursynth-bm3d-r8/libexec         --bindir=/nix/store/b1mwam4g25skl7r408phcvqhbn3i1sf0-vapoursynth-bm3d-r8/bin --sbindir=/nix/store/b1mwam4g25skl7r408phcvqhbn3i1sf0-vapoursynth-bm3d-r8/sbin         --includedir=/nix/store/b1mwam4g25skl7r408phcvqhbn3i1sf0-vapoursynth-bm3d-r8/include         --mandir=/nix/store/b1mwam4g25skl7r408phcvqhbn3i1sf0-vapoursynth-bm3d-r8/share/man --infodir=/nix/store/b1mwam4g25skl7r408phcvqhbn3i1sf0-vapoursynth-bm3d-r8/share/info         --localedir=/nix/store/b1mwam4g25skl7r408phcvqhbn3i1sf0-vapoursynth-bm3d-r8/share/locale         -Dauto_features=enabled         -Dwrap_mode=nodownload         --prefix=/nix/store/b1mwam4g25skl7r408phcvqhbn3i1sf0-vapoursynth-bm3d-r8  
The Meson build system
Version: 0.61.2
Source dir: /build/source
Build dir: /build/source/build
Build type: native build
Project name: BM3D
Project version: 8
C++ compiler for the host machine: g++ (gcc 11.3.0 "g++ (GCC) 11.3.0")
C++ linker for the host machine: g++ ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /nix/store/shgkj0lsgs0swgvrzz81dwykz6a519mf-pkg-config-wrapper-0.29.2/bin/pkg-config (0.29.2)
Run-time dependency vapoursynth found: YES 58
Run-time dependency fftw3f found: YES 3.3.10
Build targets in project: 1

BM3D 8

  User defined options
    auto_features: enabled
    bindir       : /nix/store/b1mwam4g25skl7r408phcvqhbn3i1sf0-vapoursynth-bm3d-r8/bin
    buildtype    : plain
    includedir   : /nix/store/b1mwam4g25skl7r408phcvqhbn3i1sf0-vapoursynth-bm3d-r8/include
    infodir      : /nix/store/b1mwam4g25skl7r408phcvqhbn3i1sf0-vapoursynth-bm3d-r8/share/info
    libdir       : /nix/store/b1mwam4g25skl7r408phcvqhbn3i1sf0-vapoursynth-bm3d-r8/lib
    libexecdir   : /nix/store/b1mwam4g25skl7r408phcvqhbn3i1sf0-vapoursynth-bm3d-r8/libexec
    localedir    : /nix/store/b1mwam4g25skl7r408phcvqhbn3i1sf0-vapoursynth-bm3d-r8/share/locale
    mandir       : /nix/store/b1mwam4g25skl7r408phcvqhbn3i1sf0-vapoursynth-bm3d-r8/share/man
    prefix       : /nix/store/b1mwam4g25skl7r408phcvqhbn3i1sf0-vapoursynth-bm3d-r8
    sbindir      : /nix/store/b1mwam4g25skl7r408phcvqhbn3i1sf0-vapoursynth-bm3d-r8/sbin
    wrap_mode    : nodownload

Found ninja-1.10.2 at /nix/store/ks2635sihw76nriwy8dxjdylr42bfndq-ninja-1.10.2/bin/ninja
meson: enabled parallel building
@nix { "action": "setPhase", "phase": "buildPhase" }
building
build flags: -j32 -l32
[1/10] Compiling C++ object libbm3d.so.p/source_BM3D.cpp.o
[2/10] Compiling C++ object libbm3d.so.p/source_VBM3D_Final.cpp.o
FAILED: libbm3d.so.p/source_VBM3D_Final.cpp.o 
g++ -Ilibbm3d.so.p -I. -I.. -I../include -I/nix/store/ynynkff4gvx0i602vpbyvp0372yn038q-vapoursynth-58/include/vapoursynth -I/nix/store/nnyf8kwjdrygspcy8acbhrkh8vxksms7-fftw-single-3.3.10-dev/include -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++14 -Wno-unused-local-typedefs -mfpmath=sse -msse2 -fPIC -MD -MQ libbm3d.so.p/source_VBM3D_Final.cpp.o -MF libbm3d.so.p/source_VBM3D_Final.cpp.o.d -o libbm3d.so.p/source_VBM3D_Final.cpp.o -c ../source/VBM3D_Final.cpp
../source/VBM3D_Final.cpp: In member function 'virtual void VBM3D_Final_Process::CollaborativeFilter(int, const std::vector<float*>&, const std::vector<float*>&, const std::vector<const float*>&, const std::vector<const float*>&, const Pos3PairCode&) const':
../source/VBM3D_Final.cpp:119:25: error: 'numeric_limits' is not a member of 'std'
  119 |     L2Wiener = Max(std::numeric_limits<float>::epsilon(), L2Wiener);
      |                         ^~~~~~~~~~~~~~
../source/VBM3D_Final.cpp:119:40: error: expected primary-expression before 'float'
  119 |     L2Wiener = Max(std::numeric_limits<float>::epsilon(), L2Wiener);
      |                                        ^~~~~
[3/10] Compiling C++ object libbm3d.so.p/source_BM3D_Final.cpp.o
[4/10] Compiling C++ object libbm3d.so.p/source_BM3D_Basic.cpp.o
[5/10] Compiling C++ object libbm3d.so.p/source_VBM3D_Basic.cpp.o
[6/10] Compiling C++ object libbm3d.so.p/source_VAggregate.cpp.o
[7/10] Compiling C++ object libbm3d.so.p/source_VSPlugin.cpp.o
[8/10] Compiling C++ object libbm3d.so.p/source_BM3D_Base.cpp.o
[9/10] Compiling C++ object libbm3d.so.p/source_VBM3D_Base.cpp.o
ninja: build stopped: subcommand failed.
</details>

**Comment by sbruder** [comment]
This should get fixed by https://github.com/tadeokondrak/vs-overlay/pull/4/commits/6a474a2a24d9e563fa7f225a1d1ef30bda185eeb in #4. I didn’t have much time for VapourSynth lately, so I couldn’t check that all plugins still work, but I hope to be able to merge complete it soon. In the meantime you could use #4’s branch instead of master, which should also fix many other plugins not building/working.
